################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/debug.c \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/main.c \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Radio/radio_board_if.c \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/stm32_lpm_if.c \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/stm32wlxx_hal_msp.c \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/stm32wlxx_it.c \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/system_stm32wlxx.c \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/timer_if.c \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/usart_if.c \
C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/util_if.c 

OBJS += \
./sparrow-lora/Application/Core/debug.o \
./sparrow-lora/Application/Core/main.o \
./sparrow-lora/Application/Core/radio_board_if.o \
./sparrow-lora/Application/Core/stm32_lpm_if.o \
./sparrow-lora/Application/Core/stm32wlxx_hal_msp.o \
./sparrow-lora/Application/Core/stm32wlxx_it.o \
./sparrow-lora/Application/Core/system_stm32wlxx.o \
./sparrow-lora/Application/Core/timer_if.o \
./sparrow-lora/Application/Core/usart_if.o \
./sparrow-lora/Application/Core/util_if.o 

C_DEPS += \
./sparrow-lora/Application/Core/debug.d \
./sparrow-lora/Application/Core/main.d \
./sparrow-lora/Application/Core/radio_board_if.d \
./sparrow-lora/Application/Core/stm32_lpm_if.d \
./sparrow-lora/Application/Core/stm32wlxx_hal_msp.d \
./sparrow-lora/Application/Core/stm32wlxx_it.d \
./sparrow-lora/Application/Core/system_stm32wlxx.d \
./sparrow-lora/Application/Core/timer_if.d \
./sparrow-lora/Application/Core/usart_if.d \
./sparrow-lora/Application/Core/util_if.d 


# Each subdirectory must supply rules for building sources it contributes
sparrow-lora/Application/Core/debug.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/debug.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
sparrow-lora/Application/Core/main.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/main.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
sparrow-lora/Application/Core/radio_board_if.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Radio/radio_board_if.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
sparrow-lora/Application/Core/stm32_lpm_if.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/stm32_lpm_if.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
sparrow-lora/Application/Core/stm32wlxx_hal_msp.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/stm32wlxx_hal_msp.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
sparrow-lora/Application/Core/stm32wlxx_it.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/stm32wlxx_it.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
sparrow-lora/Application/Core/system_stm32wlxx.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/system_stm32wlxx.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
sparrow-lora/Application/Core/timer_if.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/timer_if.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
sparrow-lora/Application/Core/usart_if.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/usart_if.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
sparrow-lora/Application/Core/util_if.o: C:/Users/rozzie/dev/sparrow-accelerator-sensor-firmware/sparrow-lora/Application/Core/Src/util_if.c sparrow-lora/Application/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32WL55xx -DCORE_CM4 -c -I../../sparrow-lora/Application/ -I../../sparrow-lora/Application/Core/Inc -I../../sparrow-lora/Application/App -I../../sparrow-lora/Application/Sensor -I../../sparrow-lora/Application/Core/Radio -I../../note-c -I../../sparrow-lora/Drivers/STM32WLxx_HAL_Driver/Inc -I../../sparrow-lora/Drivers/CMSIS/Include -I../../sparrow-lora/Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy -I../../sparrow-lora/Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../sparrow-lora/Utilities/lpm/tiny_lpm -I../../sparrow-lora/Utilities/misc -I../../sparrow-lora/Utilities/sequencer -I../../sparrow-lora/Utilities/timer -I../../sparrow-lora/Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-sparrow-2d-lora-2f-Application-2f-Core

clean-sparrow-2d-lora-2f-Application-2f-Core:
	-$(RM) ./sparrow-lora/Application/Core/debug.d ./sparrow-lora/Application/Core/debug.o ./sparrow-lora/Application/Core/main.d ./sparrow-lora/Application/Core/main.o ./sparrow-lora/Application/Core/radio_board_if.d ./sparrow-lora/Application/Core/radio_board_if.o ./sparrow-lora/Application/Core/stm32_lpm_if.d ./sparrow-lora/Application/Core/stm32_lpm_if.o ./sparrow-lora/Application/Core/stm32wlxx_hal_msp.d ./sparrow-lora/Application/Core/stm32wlxx_hal_msp.o ./sparrow-lora/Application/Core/stm32wlxx_it.d ./sparrow-lora/Application/Core/stm32wlxx_it.o ./sparrow-lora/Application/Core/system_stm32wlxx.d ./sparrow-lora/Application/Core/system_stm32wlxx.o ./sparrow-lora/Application/Core/timer_if.d ./sparrow-lora/Application/Core/timer_if.o ./sparrow-lora/Application/Core/usart_if.d ./sparrow-lora/Application/Core/usart_if.o ./sparrow-lora/Application/Core/util_if.d ./sparrow-lora/Application/Core/util_if.o

.PHONY: clean-sparrow-2d-lora-2f-Application-2f-Core

